### PR TITLE
added regular time above Hex time

### PR DESCRIPTION
**Pull request by Anmol-Ghadia**
3nd Response to issue #2 

My apologies for the previous PR, I have thoroughly tested this one :)

### CODE REVIEW

**Comment by rajtilakjee** [comment]
@Anmol-Ghadia did you check the code deploying on PythonAnywhere as I had suggested? This is giving the same error as earlier. Let me know if you need any help.

**Review by rajtilakjee — CHANGES_REQUESTED** [review]
Same error as before.

**Comment by Anmol-Ghadia** [comment]
I was able to successfully deploy on PythonAnywhere. Did not get any errors in the log. You can check it out [here](http://putin221.pythonanywhere.com/).

**Comment by rajtilakjee** [comment]
@Anmol-Ghadia it worked! Good job. Why don't you try your hands on the other 2 issues. I am pretty sure you would be able to solve them in no time at all.

**Pull request merged**
